/**
 * Engine-neutral description of layout behaviour.
 *
 * Scenarios are generated by running the v1 engine and stored as fixtures. The
 * same operations are later replayed through the v2 engine, which must produce
 * the same canonical structure and pixel-identical rects. Everything here is
 * keyed by tab ids so it does not depend on either engine's internal node ids.
 */

export type Direction = 'horizontal' | 'vertical'
export type Side = 'top' | 'bottom' | 'left' | 'right'
export type RectTuple = [x: number, y: number, width: number, height: number]

/** A tabset is addressed by any tab inside it. */
export type TabsetRef = { tabsetOf: string }

export type Operation =
	| {
			op: 'move'
			source: { tab: string } | TabsetRef
			target:
				| { tab: string; position: 'left' | 'right' }
				| (TabsetRef & { area: Side | 'contain' })
				| { root: Side }
	  }
	| { op: 'splitter'; before: string; after: string; point: { x: number; y: number } }
	| ({ op: 'fold' } & TabsetRef)
	| ({ op: 'maximize' } & TabsetRef)
	| { op: 'resize'; width: number; height: number }

export interface CanonicalTabset {
	tabs: string[]
	active: string
	folded?: true
}
export interface CanonicalRow {
	direction: Direction
	children: CanonicalNode[]
}
export type CanonicalNode = CanonicalRow | CanonicalTabset

export interface Observation {
	tree: CanonicalRow
	/** Tabset rects keyed by `tabs.join('|')`. */
	tabsets: Record<string, RectTuple>
	/** Splitter rects keyed by `firstTab(before) + '>' + firstTab(after)`. */
	splitters: Record<string, RectTuple>
	/** Key of the maximized tabset, if any. */
	maximized: string | null
}

export interface Step {
	operation: Operation
	/** Whether the engine accepted the operation (moves, fold, maximize). */
	accepted?: boolean
	observation: Observation
	/** v1 saved layout after this step (every few steps, used for migration checks). */
	savedV1?: unknown
}

export interface Scenario {
	name: string
	tabs: string[]
	container: { width: number; height: number }
	initial: Observation
	initialSavedV1: unknown
	steps: Step[]
}

export interface Driver {
	create(tabs: string[], container: { width: number; height: number }, saved?: unknown): void
	apply(operation: Operation): boolean | undefined
	observe(): Observation
	save(): unknown
}

export const isRow = (node: CanonicalNode): node is CanonicalRow =>
	'direction' in node

export const firstTab = (node: CanonicalNode): string =>
	isRow(node) ? firstTab(node.children[0]) : node.tabs[0]

export const tabsetKey = (tabs: readonly string[]) => tabs.join('|')

/**
 * Flattens single-child rows and same-direction nesting, which v2 does on
 * every change and v1 sometimes leaves behind (audit B7). Both engines are
 * compared in this normalized form.
 */
export function normalizeCanonical(root: CanonicalRow): CanonicalRow {
	const normalizeRow = (row: CanonicalRow): CanonicalRow => {
		const children: CanonicalNode[] = []
		for (const child of row.children) {
			if (!isRow(child)) {
				if (child.tabs.length > 0) children.push(child)
				continue
			}
			let next: CanonicalNode = normalizeRow(child)
			if (isRow(next) && next.children.length === 1) next = next.children[0]
			if (isRow(next) && next.children.length === 0) continue
			if (isRow(next) && next.direction === row.direction) {
				children.push(...next.children)
			} else {
				children.push(next)
			}
		}
		return { direction: row.direction, children }
	}

	let result = normalizeRow(root)
	while (result.children.length === 1 && isRow(result.children[0])) {
		result = result.children[0]
	}
	return result
}

/** Park–Miller PRNG: small, deterministic, identical everywhere. */
export function createRandom(seed: number) {
	let state = seed % 2147483647
	if (state <= 0) state += 2147483646
	return (n: number) => {
		state = (state * 16807) % 2147483647
		return state % n
	}
}

const SIDES: Side[] = ['top', 'bottom', 'left', 'right']

/** An operation the real UI could produce, chosen from the current observation. */
export function randomOperation(
	observation: Observation,
	random: (n: number) => number
): Operation {
	const tabsets = Object.keys(observation.tabsets).map((key) => key.split('|'))
	const tabs = tabsets.flat()
	const splitters = Object.entries(observation.splitters)
	const pick = <T>(items: T[]): T => items[random(items.length)]

	const kind = random(10)
	if (kind < 5) {
		const source =
			random(3) === 0 ? { tabsetOf: pick(tabs) } : { tab: pick(tabs) }
		const targetKind = random(5)
		const target =
			targetKind === 0
				? { root: pick(SIDES) }
				: targetKind === 1
					? { tab: pick(tabs), position: pick(['left', 'right'] as const) }
					: {
							tabsetOf: pick(tabs),
							area: pick([...SIDES, 'contain'] as const),
						}
		return { op: 'move', source, target }
	}
	if (kind < 7 && splitters.length > 0) {
		const [key, [x, y, width, height]] = pick(splitters)
		const [before, after] = key.split('>')
		const offset = random(400) - 200
		const isVerticalBar = width < height
		return {
			op: 'splitter',
			before,
			after,
			point: isVerticalBar
				? { x: x + width / 2 + offset, y: y + height / 2 }
				: { x: x + width / 2, y: y + height / 2 + offset },
		}
	}
	if (kind < 8) return { op: 'fold', tabsetOf: pick(tabs) }
	if (kind < 9) return { op: 'maximize', tabsetOf: pick(tabs) }
	return {
		op: 'resize',
		width: 200 + random(1400),
		height: 150 + random(900),
	}
}

/** Runs `stepCount` random UI operations and records what the driver does. */
export function recordScenario(
	driver: Driver,
	name: string,
	tabs: string[],
	container: { width: number; height: number },
	seed: number,
	stepCount: number,
	saveEvery = 5
): Scenario {
	const random = createRandom(seed)
	driver.create(tabs, container)
	const initial = driver.observe()
	const scenario: Scenario = {
		name,
		tabs,
		container,
		initial,
		initialSavedV1: driver.save(),
		steps: [],
	}

	let observation = initial
	for (let i = 0; i < stepCount; i++) {
		const operation = randomOperation(observation, random)
		const accepted = driver.apply(operation)
		observation = driver.observe()
		const step: Step = { operation, observation }
		if (accepted !== undefined) step.accepted = accepted
		if ((i + 1) % saveEvery === 0) step.savedV1 = driver.save()
		scenario.steps.push(step)
	}
	return scenario
}
