name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/ci-setup
      - uses: ./.github/actions/ci-checks
